package src;

import com.mysql.cj.util.StringUtils;

import src.constants.Constants;
import src.constants.Constants.RULE;
import src.database.DBConnection;
import src.services.*;

import java.sql.*;

/**
 * Main class for Fraud Detection
 */
public class FraudDetection {

    private static DBConnection dbConnection;
    private static Connection connection;

    /**
     * Main function to run the Project
     */
    public static void main(String args[]) {
        System.out.println("\n" + "#".repeat(100));
        connectToDatabase();
        verifyDatabase();

        clearTables();
        applyRules();
        printFrauds();

        dbConnection.closeConnection();
    }

    /**
     * Gets the Databse Singleton Instance
     */
    private static void connectToDatabase() {
        dbConnection = DBConnection.getInstance();
        connection = dbConnection.getConnection();
        System.out.println("\nConnected to Database");
    }

    /**
     * Verifies the schema is setup correctly, with tables account_info and transactions
     */
    private static void verifyDatabase(){
        try {
            Statement stmt=connection.createStatement();  
            ResultSet rs=stmt.executeQuery("select count(1) as n_accounts from account_info");
            if(rs.next()) {
                int n_accounts = rs.getInt("n_accounts");
                // System.out.println("n_accounts: "+n_accounts);
                if(n_accounts==0){
                    throw new Exception("MySQL database dump missing. Follow README file instructions");
                }
            } 

            rs = stmt.executeQuery("select count(1) as n_transactions from transactions");
            if(rs.next()) {
                int n_transactions = rs.getInt("n_transactions");
                // System.out.println("n_transactions: "+n_transactions);
                if(n_transactions==0){
                    throw new Exception("MySQL database dump missing. Follow README file instructions");
                }
            } 
            System.out.println("Passed Database Verification");
        }
        catch(Exception e) { 
            System.out.println(e.getMessage());
            System.exit(0);
        }
    }

    /**
     * Helper function to clear contents of all tables before stating the main logic
     */
    private static void clearTables() {
        for(RULE r:RULE.values()){
            if(!StringUtils.isEmptyOrWhitespaceOnly(r.getTableName())){
                clearTable(r.getTableName());
            }
        }
        clearTable("transaction_range");
    }

    private static void clearTable(String tableName) {
        String query = "delete from "+tableName;
        try{
            Statement stmt = connection.createStatement();
            stmt.executeUpdate(query);
            // System.out.println(tableName+" cleared");
        }catch(Exception e){
            System.out.println(e.getMessage());
            System.out.println(e.getStackTrace());
        }
    }

    /**
     * Applies all the Rules as stated by the RULE enum in src/constants/Constants.java
     */
    private static void applyRules() {
        System.out.println("\nStarting Fraud Detection...");
        for(RULE r:RULE.values()){
            r.applyRule();
        }
    }

    /**
     * Prints all the frauds generated by applying the Rules 
     * as stated by the RULE enum in src/constants/Constants.java
     * Also, exports them to seperate CSV files in output/ directory.
     */
    private static void printFrauds() {
        // System.out.println("\nPrinting Fraud Transactions...");  
        for(RULE r:RULE.values()){
            if(!StringUtils.isEmptyOrWhitespaceOnly(r.getTableName())){
                System.out.println("\n"+"#".repeat(30)
                                    + " Fraud Transactions according to " + r.getName() 
                                    + " "+"#".repeat(30));

                UtilsService.exportTableToCSVFile(Constants.OUTPUT_FILE_PATH + r.getTableName()+".csv", 
                                                    r.getTableName());
                UtilsService.printTableToScreen(r.getTableName());
            }
        }
    }
}